### ISSUE TITLE
Unity3D prefabs

### ISSUE THREAD

**Issue by ST-Apps** [PoGo-Devs/PoGo-3D-Assets#14]
I don't know if any of you has experience with Unity3D, but I started doing some tests and I've been able to build the catching part in Unity3D and add it to the current app.

So, let's get to my request: what I need is to have each of the models named `{PokemonEnglishName}.fbx` (same names as in `PokemonIn` enum) and with a mesh/box collider already baked in the prefab.

In my tests I've been using the mesh collider, but this requires the throw to be really perfect to catch the Pokemon, so a box collider 2 times bigger than the model should be enough.

Also, I need the models to have their size normalized: as for now, some of them are really too small compared to the others (for example I see Drowzee like 10 times smaller than Bulbasaur).

I know that it's a though work but I think it is more important than having the animations, so that we can start building a physics based catching system.

**Comment by MadoxLabs** [comment]
Thats awesome! If you can get Unity integrated that easily (don't really know how easy it was but still, you did it!) then that's surely the way to go.  Seems like that will be a lot less effort to use Unity, overall.  Anyhow, I know nothing about Unity and with things happening to me lately, its hard to find a lot of time or motivation to do what I wanted to do.  So I'll be stepping aside. If anyone needs my code for some reason, its public.  Looking forward to seeing how it goes

**Comment by ST-Apps** [comment]
@MadoxLabs actually your work is quite needed because I can't use Unity for the map or for Pokemon details page. This one's just a rough idea for the future, but it's only limited to the catching screen.

**Comment by MadoxLabs** [comment]
Well I know Unity is a much more robust rendering engine than I can provide, and its something Unity devs can jump on as opposed to needing to learn my code :p    I can keep going though. I was going to split my stuff into 2 forks to get the rendering code separate from the AR code

**Comment by wannefab** [comment]
@ST-Apps Sounds cool! I once did some work with Unity, seems to be good a option.
I hope I can work on the models this week. I guess I can just put a box around the pokemon and you can use it as collider and hide it for the eye? I'm not quiet sure how to adjust the size because of the skeleton, but we can manage this somehow (can't check right now because my surface is in service and i'm on the road...)

**Comment by ST-Apps** [comment]
@Lithagon There's no need to use a real box.
- create an empty Unity3D project
- drag the FBX model
- go to Hierarchy and select the dragged model
- in model's properties click "add component"
- select "box collider"
- set Y center to 1, scale all to 2
- drag the model from Hierarchy to another folder in Unity and it will create the .prefab file with the included collider

**Comment by wannefab** [comment]
ahhh of course! Perfect. I'll look into it, but i'm short of time at the moment...

**Comment by wannefab** [comment]
@ST-Apps How do you need the Data? Is one Package of all Pokemon containing the Prefabs ( {PokemonEnglishName}.prefab ) ok? You will find it in the Unity folder ( PokemonGen1_Prefabs.unitypackage ). If it's good like this i will continue

**Comment by ST-Apps** [comment]
@Lithagon It's good, just place them under Resources folder (create it and move all the models there). Final structure should be `Resources/Pokemon/{english_name}.fbx`

**Comment by wannefab** [comment]
@ST-Apps I've been working on it today: I did import all textured models and fixed some occuring issues and I made FBX placeholders with pictures for the models we don't already have ready so we can replace them later, some require a lot of work.
I'm not sure when I will have time to finish the prefabs, certainly not tomorrow...

**Comment by ST-Apps** [comment]
Take your time, it's not something that I've planned for the next release :)

**Comment by wannefab** [comment]
@ST-Apps The Prefabs are done, it will be playable like this, you have all 151 pokemon in it. But we have to finish the models and replace the flat placeholders (around 40 models). We can also try out animations in unity i guess ^^

**Comment by Firestarthirty** [comment]
Perfect! Unity also supports .blend!

**Comment by Firestarthirty** [comment]
Merging this will be hard, we may need to finish then pause all merging until we can incorporate this

**Comment by Firestarthirty** [comment]
This may be a little crazy but I'm working on rewriting the entire UI for Unity

**Comment by Firestarthirty** [comment]
Afterall, that's how the Original works

**Comment by Firestarthirty** [comment]
I'm just gonna work on Animating them all
